### ISSUE TITLE
type *pe.File has no field or method NetCLRVersion

### ISSUE THREAD

**Issue by nodauf** [Binject/go-donut#7]
I built a project with the version `v0.0.0-20200818232812-e80b835e4a65`. I recently tried to upgrade to the latest version and I have the following error.

```
go\pkg\mod\github.com\!binject\go-donut@v0.0.0-20201215224200-d947cf4d090d\donut\donut.go:42:35: pefile.NetCLRVersion undefined (type *pe.File has no field or method NetCLRVersion)
```

It seems located inside the go-donut project. Is the usage changed or is it an issue in go-donut ?

**Comment by awgh** [comment]
You need to update github.com/Binject/debug, which is where this method was added.

You're trying to build the latest version of go-donut with an outdated version of one of the dependencies.

go get -u github.com/Binject/debug

or:

go get -u github.com/Binject/go-donut/...

**Comment by nodauf** [comment]
Ok thank you :)

**Comment by awgh** [comment]
Also, as a result of this change, go-donut now automatically detects .NET payloads and does the right thing, just like real donut.  So if you were using the --dotnet flag, that's gone now.

It'll also automatically detect the minimum .NET version from the payload.  If you were manually setting the version, that will override the auto-detected one, so you probably want to stop setting the version manually too.

Breaking change, but definitely worth it.

**Comment by nodauf** [comment]
Nice work. Awesome
